on:
  push:
    tags:
      - v[0-9]+.*

name: Publish
permissions: {}

jobs:
  crates_publish:
    name: Publish (crates.io)
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Update Rust toolchain
        run: rustup upgrade

      - name: Logon to Crates
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: "Publish"
        run: cargo publish