name: Rust PR Actions

on:
  pull_request:
    branches:
      - "main"
      - "vnext"

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  build:
    name: "Build and Run tests"
    strategy:
      fail-fast: false
      matrix:
        info:
          - os: "macos-latest"
            target: "x86_64-apple-darwin"
          - os: "macos-latest"
            target: "aarch64-apple-darwin"
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - os: "windows-11-arm"
            target: "aarch64-pc-windows-msvc"
    runs-on: ${{ matrix.info.os }}
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Update Rust toolchain
        run: rustup upgrade

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          save-if: false
      - name: Fmt Check
        run: cargo fmt -- --check
      
      - name: Run clippy action to produce annotations
        run: cargo clippy

      - name: Download test files (macOS)
        if: matrix.info.os == 'macos-latest'
        run: cd tests && wget -O ./test_data.zip https://github.com/mandiant/macos-UnifiedLogs/releases/download/v1.0.0/test_data.zip && unzip test_data.zip

      - name: Download test files (Linux)
        if: matrix.info.os == 'ubuntu-latest'
        run: cd tests && wget -O ./test_data.zip https://github.com/mandiant/macos-UnifiedLogs/releases/download/v1.0.0/test_data.zip && unzip test_data.zip

      - name:  Download test files (Windows)
        if: matrix.info.os == 'windows-latest'
        run: |
          cd tests
          Invoke-WebRequest -Uri "https://github.com/mandiant/macos-UnifiedLogs/releases/download/v1.0.0/test_data.zip" -OutFile "./test_data.zip"
          Expand-Archive -Path "./test_data.zip" -DestinationPath "." -Force
        shell: pwsh

      - name:  Download test files (Windows ARM)
        if: matrix.info.os == 'windows-11-arm'
        run: |
          cd tests
          Invoke-WebRequest -Uri "https://github.com/mandiant/macos-UnifiedLogs/releases/download/v1.0.0/test_data.zip" -OutFile "./test_data.zip"
          Expand-Archive -Path "./test_data.zip" -DestinationPath "." -Force
        shell: pwsh

      - name: Build tests
        run: cargo test --no-run --release
      - name: Run tests
        run: cargo test --release